apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-watch
  labels:
    app: pod-watch
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: pod-watch
  template:
    metadata:
      labels:
        app: pod-watch
    spec:
      containers:
        - name: pod-watch
          image: ghcr.io/gowtham-ra/psbl-watch:latest
          imagePullPolicy: Always
          env:
            - name: PUSHOVER_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pushover-creds
                  key: PUSHOVER_APP_TOKEN
            - name: PUSHOVER_USER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pushover-creds
                  key: PUSHOVER_USER_TOKEN
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532  # UID for "nonroot" user in distroless
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
